site_name: FAST by Eyevinn Technology
site_url: https://fast.eyevinn.technology
site_description: The Sustainable FAST Channel Engine
site_author: Eyevinn Team
nav:
  - Home: index.md
theme:
  name: mkdocs
  locale: en
  
copyright: Copyright &copy; 2022 <a href="https://www.eyevinn.se">Eyevinn Technology AB</a>