site_name: FAST by Eyevinn Technology
site_url: https://fast.docs.eyevinn.technology
site_description: The Sustainable FAST Channel Engine
site_author: Eyevinn Team
nav:
  - Home: index.md
  - Plugins: 
    - Available Plugins: plugins.md
    - Schedule Service: plugins/schedule_service.md
  - Origin Services:
    - Overview: origins.md
    - AWS MediaPackage: origin/aws_mediapackage.md
  - Schedule Service: schedule_service.md
  - Release notes: changelog.md
theme:
  name: material
  
use_directory_urls: false

copyright: Copyright &copy; 2022- <a href="https://www.eyevinn.se">Eyevinn Technology AB</a>