apiVersion: v1
kind: Service
metadata:
  name: fast-engine-service
spec:
  type: NodePort
  selector:
    app: fast-engine
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 30000
