name: Upload artifacts when creating a tag

on:
  push:
    tags:
      - 'v*'

jobs:
  upload_artifact:
    name: Attach artifact to release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/upload-artifact@v3
      with:
        name: docker-compose.yml
        path: docker-compose.yml