name: Update Landing page

on:
  push:
    branches:
      - main
    paths:
    - website/index.html
    - .github/workflows/landingpage.yml

jobs:
  updatelandingpage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1
          with:
            node-version: 16
            registry-url: https://registry.npmjs.org/
      - name: build 
          run: |
            npm ci
            npm run build:lp
      - name: Deploy docs to S3 bucket
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: 'origin-web-fast'
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_AWS_ACCESS_KEY_ID  }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'eu-north-1'
          SOURCE_DIR: 'dist-website/'
    
